version: '3.7'

volumes:
  database_volume:

services:
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/postgresql/data
    networks:
      - Trans

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    restart: always
    env_file:
      - .env
    networks:
      - Trans

  backend:
    image: backend
    build: ./requirements/backend
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
    env_file:
      - .env
    volumes:
      - ./requirements/backend/transc-backend:/usr/src/app
    networks:
      - Trans

  frontend:
    image: frontend
    build: ./requirements/frontend
    container_name: frontend
    ports:
      - "8000:3000"
    restart: always
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./requirements/frontend/transc-frontend:/usr/src/app
    networks:
      - Trans

networks:
  Trans:
    driver: bridge