version: '3.7'

volumes:
  database_volume:

services:
  database:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - database_volume:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    restart: always
    env_file:
      - .env

  backend:
    build: ./requirements/backend
    container_name: backend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    build: ./requirements/frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend
    env_file:
      - .env