-- AlterTable
ALTER TABLE "Game" ALTER COLUMN "ball_x" SET DEFAULT 0,
ALTER COLUMN "ball_y" SET DEFAULT 0,
ALTER COLUMN "player1_x" SET DEFAULT 0,
ALTER COLUMN "player1_y" SET DEFAULT 0,
ALTER COLUMN "player2_x" SET DEFAULT 0,
ALTER COLUMN "player2_y" SET DEFAULT 0;
