export interface GameEntity {
    W_screen : number,
    H_screen : number,
    ball_x : number,
    ball_y : number,
    vx : number,
    vy : number,
    paddle1_x : number,
    paddle2_x : number,
    paddle1_y : number,
    paddle2_y : number,
    w_paddle : number,
    h_paddle : number,
    playerSpeed : number,
}